[package]
name = "algorithm"
version = "1.1.0"
description = "Algorithm: an automation app"
authors = ["PintaPontus"]
license = "GNUv3"
repository = "https://github.com/PintaPontus/Algorithm"
default-run = "algorithm"
edition = "2021"
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.4.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.4.0", features = [ "dialog-all", "path-all", "window-close", "window-set-min-size"] }
mouse-rs = "0.4"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem and the built-in dev server is disabled.
# If you use cargo directly instead of tauri's cli you can use this feature flag to switch between tauri's `dev` and `build` modes.
# DO NOT REMOVE!!
custom-protocol = [ "tauri/custom-protocol" ]
